from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor

from ..items import OercommonsItem

class OercommonsSpider(CrawlSpider):
    name = "oercommons"
    allowed_domains = ["oercommons.org"]
    start_urls = ['https://www.oercommons.org/browse?batch_size=100&sort_by=title&view_mode=summary',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=1900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=2900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=3900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=4900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=5900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=6900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=7900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=8900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=9900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=10900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=11900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=12900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=13900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=14900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=15900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=16900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=17900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=18900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=19900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=20900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=21900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=22900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=23900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=24900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=25900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=26900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=27900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=28900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=29900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=30900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=31900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=32900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=33900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=34900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=35900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=36900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=37900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=38900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=39900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=40900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=41900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=42900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=43900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=44900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=45900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=46900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=47900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=48900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=49900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=50900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=51900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=52900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=53900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=54900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55800',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=55900',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56000',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56100',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56200',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56300',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56400',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56500',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56600',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56700',
                  'https://www.oercommons.org/browse?batch_size=100&batch_start=56800']

    rules = (
        # Rule(LinkExtractor(allow="batch_start"), callback="load_page"),
        Rule(LinkExtractor(allow=("courses","courseware","authoring"), deny="add"), callback="parse"),
    )

    def parse(self, response):

        license = response.css('[rel="license"]::text').get()
        if not license: license = response.css(".material-details-second-part .text").get()
        if license:
            license = license.replace('<dd class="text">', "").split("<img", 1)[0]
        else:
            license = ""
        lvl = response.css('dd')[2].get().replace("\n", "").replace("<dd>", "").replace("</dd>", "").replace(
            '<span class="tx">', "").replace("</span>", "")
        item = OercommonsItem()
        item["_id"] = response.url
        item["title"] = response.css('h1 [itemprop="name"]::text').get()
        item["description"] = response.css('[itemprop="description"]::text').get()
        item["subject"] = response.css('[itemprop="about"]::text').getall()
        item["level"] = lvl.lstrip(' ').rstrip(' ').split(",")
        item["material_type"] = response.css('[itemprop="learningResourceType"]::text').get()
        item["author"] = response.css('[itemprop="author"] a::text').getall()
        item["date_added"] = response.css(".text::text")[1].get()
        item["license"] = license.replace("\n", "").lstrip(' ').rstrip(' ')
        item["language"] = response.css('[itemprop="inLanguage"]::text').get()
        item["lor"] = "oercommons"
        item["rating"] = response.css('.stars::attr(data-rating-value)')[0].extract()
        item["number_visits"] = response.css('.counter-item:nth-child(1) span:nth-child(3)::text').get()
        item["number_saves"] = response.css('.counter-item:nth-child(2) span:nth-child(3)::text').get()

        yield item

    # def parse_item(self, response):
    #     yield {
    #         "title": response.css('h1 [itemprop="name"]::text').get(),
    #         "url": response.url,
    #         "description":  response.css('[itemprop="description"]::text').get(),
    #         "subject": response.css('[itemprop="about"]::text').get(),
    #         "level": response.css('dd::text')[3].get().replace("\n", "").lstrip(' ').rstrip(' '),
    #         "material_type": response.css('[itemprop="learningResourceType"]::text').get(),
    #         "author": response.css('[itemprop="author"] a::text').getall(),
    #         "date_add": response.css(".text::text")[1].get(),
    #         "license": response.css('[rel="license"]::text').get().replace("\n", "").lstrip(' ').rstrip(' '),
    #         "language": response.css('[itemprop="inLanguage"]::text').get(),
    #         "lor": "oercommons",
    #         "rating": response.css('.stars::attr(data-rating-value)')[0].extract()
    #     }
    #
    #
    # def load_page(self,response):
    #     next_page = response.css('.pagination a::attr(href)').extract()
    #     if next_page:
    #         next_href = next_page[0]
    #         next_page_url = 'https://www.oercommons.org' + next_href
    #         request = scrapy.Request(url=next_page_url)
    #         yield request